### ISSUE TITLE
No encuentro el instalador 

### ISSUE THREAD

**Issue by bernivalle** [AlphaCentaury/MovistarTV#11]
No encuentro el instalador de ninguna de las versiones disponibles.
Espero me puedan ayudar con un enlace para su descarga.
Gracias

**Comment by elvisaloha** [comment]
Yo tampoco. ¿Alguien podría decir dónde encontrar el instalador?
Gracias

**Comment by AlphaCentaury** [comment]
Hola. Al pasar Codeplex al modo de "archivo", incomprensiblemente se han eliminado todas las descargas.
Las acabo de añadir en GitHub.

Las descargas pueden encontrarse a través de la [Home de la Wiki](https://github.com/AlphaCentaury/MovistarTV/wiki)

Para la **versión 1.5 'Kruger 60' beta**, las descargas están en [**Descarga v1.5 beta 0**](https://github.com/AlphaCentaury/MovistarTV/wiki/Descarga-v1.5-beta-0)

**Comment by elvisaloha** [comment]
Gracias!
