### ISSUE TITLE
1.5.1010.0 (Beta 1 RC2 ) uso de CPU y EPG

### ISSUE THREAD

**Issue by dmnmsc** [AlphaCentaury/MovistarTV#14]
Hola,

Estoy probando 1.5 RC2 y veo que el channel.list tiene un uso de CPU ligeramente superior a la versión anterior. Por lo poco que he visto el EPG sigue cargando (o al menos su animación) pese a haber obtenido ya toda la guía.

![image](https://user-images.githubusercontent.com/8472142/75090500-dd3b5d80-5563-11ea-817c-c11ad9621888.png)

No sé si está relacionado o no, ni si quieres feedback de esta versión. Veo que ha mejorado la obtención de logos y EPG (canales autonómicos). 

Muchas gracias!

**Comment by AlphaCentaury** [comment]
Hola. Claro que agradezco cualquier tipo de feedback.

La verdad, no había mirado los niveles de consumo de recursos de la aplicación, tando de CPU como de memoria, Gracias por comentarlo.

Seguramente el mayor uso de CPU tenga que ver, como bien apuntas, con la descarga en segundo plano de la EPG.

La razón por la cual la EPG (abreviada) se descarga de manera indefinidatiene dos motivos fundamentales:

- No es posible saber cuándo ha terminado la descarga, pues, a diferencia de la EPG completa, no existe una lista de los paquetes que hay que descargar, y éstos se reciben por multicast.
- Aún asumiendo que, mediante algún tipo de algoritmo "inteligente" se supiera cuando se ha recibido la EPG abreviada de forma completa (por ejemplo, al recibir por tercera vez la información de todos los canles), resulta más sencillo descargar continuamente la EPG y así tener siempre actualizada la lista de los siguientes programas.

Obviamente, se podría determinar cuándo resulta necesario volver a actualizar la guía (al detectar que va a "caducar" la información de algún canal), deteniendo hasta entonces la descarga.
De hecho, el deco de movistar está descargando continuamente la EPG abrevidada.

Salvo que el uso de la CPU sea considerable, y por sencillez de implementación, de momento la EPG abreviada se descargará de manera indefinida. Le echaré un vistazo de todos modos.

Cuando implemente la EPG completa (que requiere decodificar la información mandada por movistar+), al sí disponer de la lista de los paquetes a descargar, una vez descargada por completo su descarga parará hasta pasar, digamos, 12 horas.

**Comment by dmnmsc** [comment]
No es nada preocupante eh. Estamos hablando de una diferencia ínfima. Mientras en la versión anterior el proceso está al 0%, en la nueva versión va oscilando entre el 0-1% constantemente. He imaginado que era por la animación de descarga de EPG (y no por la descarga en sí misma). Pero tras leer tu explicación no creo que sea nada que deba preocuparnos.
