### ISSUE TITLE
El programa no puede arrancar si desinstalas un reproductor configurado en IPTViewr

### ISSUE THREAD

**Issue by dmnmsc** [AlphaCentaury/MovistarTV#15]
Si añades un reproductor en la configuración de IPTViewr y desinstalas dicho reproductor de tu sistema el programa no puede arrancar. La única solución es editar el user-config.xml y remover dicha entrada de la configuración.

**Comment by AlphaCentaury** [comment]
Gracias por notificar este problema. Lo miraré, y añadiré una solución en la RC3 de la beta 1.

**Comment by AlphaCentaury** [comment]
Al cargar el archivo de configuración, se ejecuta una autocomprobación del mismo, para validar que sea correcto.

Al validar el contenido de la etiqueta `<TvPlayer>`, una de las comprobaciones es validar si el archivo especificado en `<Path>`existe o no.
Si no existe, da por no válido el contenido y genera un error en `IpTviewr.UiServices.Configuration.Settings.TvPlayers.Validate()`.
Este error se propaga hasta llegar a `AppConfig.ProcessXmlConfigurationItems()` y a `AppConfig.Load`, que es la función invocada para cargar la configuración de la aplicación durante la fase de arranque.

> No se ha localizado el reproductor de TV '{nombre del reproductor' en '{ubicación}'.

La solución: no realizar la validación durante el proceso de lectura de la configuración y, si acaso, validarlo a posteriori.

**Comment by AlphaCentaury** [comment]
Al no validar durante el arranque que todos los reproductores existan, ésto provoca más errores en cascada:

1. Al intentar reproducir un canal, si el reproductor desinstalado es el reproductor por defecto.
> Se ha producido un error al procesar su solicitud
> Ninguna información ha sido proporcionada en cuanto a dónde ni por qué ocurrio el error. Los detalles del error se muestran a continuación:
> No se puede encontrar el archivo especificado.
>  C:\Program Files\Media Player\mplayer.exe (IpTViewr.Core)

2. Al seleccionar un reproductor mediante el menú contextual `Ver con reproductor...` o mediante el menú `Canal | Ver canal usando...`.
    Al aceptar el error, la lista de reproductores aparece vacía.
> Se ha producido un error al procesar su solicitud
> Ninguna información ha sido proporcionada en cuanto a dónde ni por qué ocurrio el error. Los detalles del error se muestran a continuación:
> C:\Program Files\Media Player\mplayer.exe (System.Drawing)

3. Al intentar editar la configuración de los reproductores, mediante el menú `IPTViewr | Configuración` y la opción `Reproductores`.
    Se muestra el mismo error que en caso anterior, mostrándose, de nuevo, la lista de reproductores vacía.

En cualquier caso, estos errores también sucederían si se desinstala el reproductor durante el uso del programa.

**Comment by AlphaCentaury** [comment]
En el caso 1, el error se produce en ` IpTviewr.Core.ExternalTvPlayer.Launch()`, que genera una excepción `FileNotFoundException`, la cual no es gestionada en ` IpTviewr.Core.ExternalTvPlayer.ShowTvChannel()`.

La solución: `ShowTvChannel()` debe atrapar cualquier excepción que se produzca en `Launch()`y mostrar un mensaje de error adecuado.

En los casos 2 y 3, el error se produce en `IpTviewr.UiServices.Configuration.Settings.TvPlayers.TvPlayersSettings.GetPlayerIconKey()` al llamar a la función `System.Drawing.Icon.ExtractAssociatedIcon()`.
Estas funciones se llaman para conseguir el icono del programa y ponerlo en la lista.

La solución: comprobar la existencia del reproductor antes de añadirlo a lista.
En el caso 2, si no existe, no añadir el reproductor a la lista.
En el caso 3, si no existe, añadir un icono de error.
