### ISSUE TITLE
Problemas con un canal (se oye pero no se ve)

### ISSUE THREAD

**Issue by XxZeroQxX** [AlphaCentaury/MovistarTV#17]
Antes de nada gracias por el programa y por el trabajo hecho y espero que sigas evolucionando el programa porque es una pasada, bueno a lo que íbamos jejeje, tengo problemas con un canal el canal en cuestión es el odisea HD y SD, le doy y se abre pero la imagen no se ve pero oigo el programa sabes de alguna manera de solucionar ese problema o estas trabajando en algún tipo de parche para solucionar el problema ya que ese canal me gusta mucho por los documentales que hacen.

**Comment by AlphaCentaury** [comment]
No es problema del programa, ni realmente del canal.
Movistar+ está encriptando (protegiendo) de manera progresiva sus canales, con Nagra.

Lis canales encriptados presentan ese problema: se ven, pero no se oyen.

Hasta donde yo sé, el algoritmo de encriptación es muy complejo y difícil de "romper".

Así que no hay ninguna solución rápida.
________________________________

**Comment by XxZeroQxX** [comment]
Gracias.

**Comment by AlphaCentaury** [comment]
Me ha llegado el siguiente informe:
> Los canales 46 (M Liga) y 50 (M Liga de Campeones) apenas se ven un poco en la parte superior y muy pixelados., el resto de la ventana del VLC se queda negra; el sonido si es correcto.

**Comment by panda333444** [comment]
Gracias por este programa. Ha sido fabuloso mientras funcionaba todos estos años...

Desde el domingo han aparecido unos cuantos canales encriptados de video, audio bien. El 17, el 18, algún otro.
¿Tienes alguna nueva solución para el problema?

Un saludo

**Comment by AlphaCentaury** [comment]
Hola. Perdona por el retraso.

No se trata de un fallo ni del VLC ni del programa ni de tu conexión,
Desafortunadamente, movistar está encriptando (codificando con DRM) progresivamente los canales y no hay solución sencilla.

Así que en algún momento no muy lejano este programa dejará de tener utilidad. Es una de las razones por las que tengo parado el desarrollo.
