### ISSUE TITLE
Descargar Exception message box

### ISSUE THREAD

**Issue by baskonistaatope** [AlphaCentaury/MovistarTV#24]
Soy incapaz de conseguir descar el Microsoft Exception Message Box .
Parece que microsoft lo ha borrado.... alguno teneis el instalable por ahi? o sabeis donde lo puedo conseguir o compartirmelo por dropbox wetransfer o algo asi? 

gracias!

**Comment by AlphaCentaury** [comment]
Hola. El redistribuible forma parte de la instalación. Normalmente, en el asistente de configuración inicial se muestra un enlace para lanzar el ejecutable del instalador.

No obstante, debe coincidir el idioma del instalador con el de tu ordenador. Si la interfaz de usuario te sale en Inglés, necesitas el instalador en Inglés, pues el instalador en Español sólo lleva los instaladores en español.

Si, por lo que sea, el asistente detecta que el redistribuible no es el adecuado, siempre se puede ejecutar de forma manual buscando el archivo adecuado en la carpeta `bin\redist`

Espero que te sirva.
Saludos,
Alpha
