### ISSUE TITLE
Error durante la verificación de canales

### ISSUE THREAD

**Issue by retrue** [AlphaCentaury/MovistarTV#8]
Parece ser que estoy estrenando esto.
Versiones 1.5 alpha 3 y alpha 4.
Tengo contratado el paquete de canales normal incluido con Fusión, sin nada extra, y en definición estándar porque es a través de ADSL. Mi proveedor de servicios es Andalucía.
A hacer la verificación de canales y llegar al canal Reserva 7, recibo un mensaje de error: "Se ha producido un error durante la verificación y se ha finalizado". A partir de ahí deja de verificar.
Si intento abrir el canal Reserva 7 recibo el siguiente error de VLC: "Su entrada no puede abrirse:
VLC es incapaz de abrir el MRL «rtp://@39.0.3.106:8208». Vea el registro para más detalles."
Recibo el mismo error de VLC si intento abrir  Reserva 3 HD. Parece ser que solo son esos dos los canales problemáticos.

**Comment by AlphaCentaury** [comment]
Gracias por informar del error. Confirmo que el error existe y sucede en todas las versiones alpha y en la beta 0.

![issue 8](https://cloud.githubusercontent.com/assets/13358683/18369832/67499f2e-7628-11e6-8c1c-89fd707ff0ff.png)

Aunque el verificador de canales es probado de manera periódica, efectivamente hay un problema con el verificador de canales activos, que se ha manifestado en esta ocasión por un error en la información recibida de movistar+ con respecto a algunos canales.

Te confirmo que tanto el `Reserva 7` como el `Reserva 3 HD` tienen mal la dirección. De igual modo, el `Reserva 2 HD`, aunque correcto, utiliza una dirección fuera del rango interno de direcciones de movistar+.
Este error sucede en todas las comunidades autónomas, no es sólo un problema de la demarcación de Andalucía.

En términos técnicos, la dirección del canal que se intenta verificar `rtp://@39.0.3.106:8208` no es una dirección válida de multidifusión. Por ese mismo motivo, VLC tampoco puede "abrir" el canal, porque la dirección no es válida para rtp.

El problema que tiene el verificador es que no tiene en cuenta que puede recibir direcciones incorrectas y por eso finaliza cuando tiene un error inesperado.

Anoto este problema y espero que quede resuelto en la beta 1.

**Comment by retrue** [comment]
Curioso, curioso, hace semanas que apareció este error y ahora acabo de probar desde la beta 0 y la alpha 4, y parece ser que han corregido el problema desde Movistar. Ni Reserva 7 ni Reserva 3 HD dan ya error al intentar abrirlos desde VLC ni tampoco detienen el verificador de canales.
De todos modos el bug debe corregirse por si aparecen nuevamente direcciones ip incorrectas en el futuro.
239.0.3.106:8208 es la dirección correcta para Reserva 7. Se habían comido el 2 inicial en la ip y ya lo han corregido.

**Comment by AlphaCentaury** [comment]
Faltaba un try/catch al inicializar el socket
Se ha aprovechado para hacer el código más claro y sencillo

Este error aparecerá ya corregido en la beta 1
