### ISSUE TITLE
Error durante la actualización de canales

### ISSUE THREAD

**Issue by ghost** [AlphaCentaury/MovistarTV#9]
Parece que la IP de descubrimiento de canales no funciona.

**Comment by AlphaCentaury** [comment]
La IP es correcta y funciona (al menos) hasta la semana pasada (hoy es día 27/05/2019).
Seguramente tienes un problema con la recepción de paquetes multicast. Es un problema relativamente corriente si tienes varios adaptadores de red. La "solución" es desactivar (al menos temporalmente) todos los adaptadores de red, excepto el de la ethernet (no te recomiendo usar WiFi, al menos inicialmente).
Si así funciona es un problema de que alguno de los adaptadores deshabilitados "roba" los paquetes de información de multicast antes de que lleguen al driver. Creo recordar que Windows solo admite una interfaz para la recepción multicast, y la instalación de otros drivers o tarjetas puede causar que se altere el orden de recepción.
Una vez comprobado que deshabilitando todo, menos la ethernet, funciona bien el programa, puedes ir habilitando uno a uno el resto de adaptadores.
A veces, con solo deshabilitar la ethernet y volver a habilitarla el problema se arregla "por si solo", pues Windowsdebe cambiar ´la prioridad de recepción.
Aunque la descripcion es muy técnica, espero que esta respuesta sirva para quienes se encuentren con un problema similar.
